/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Desgin;

/**
 *
 * @author ZARYAB KHAN
 */
public class AdminRegistration extends javax.swing.JFrame {

    /**
     * Creates new form AdminRegistration
     */
    public AdminRegistration() {
        initComponents();
        Validation2.setVisible(false);
        Validation1.setVisible(false);
        int id = 1;
        String str = String.valueOf(id);
        Unique_Id.setText("#"+str);
         /*try{
            int id=1;
            //Connection con = ConnectionProvider.getCon();
            //Statement st = con.createStatement();
            //ResultSet rs = st.executeQuery("select max(id) from member");
            /while(next())
            {
                id=rs.getInt(1);
                id=id+1;
                String str=String.valueOf(id);
                jLabel3.setText(str);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }*/
        
    }
    private void clear(){
        Password.setText(null);
        RePassword.setText(null);
        if(CheckBox.isSelected()){
            CheckBox.setSelected(false);
        }
        
    }
    private void clearField(){
        FirstName.setText(null);
        LastName.setText(null);
        CryptonainName.setText(null);
        Email.setText(null);
         Password.setText(null);
        RePassword.setText(null);
        if(CheckBox.isSelected()){
            CheckBox.setSelected(false);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Unique_Id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        L3 = new javax.swing.JLabel();
        CryptonainName = new javax.swing.JTextField();
        L4 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        L5 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        L6 = new javax.swing.JLabel();
        RePassword = new javax.swing.JPasswordField();
        CheckBox = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        Validation2 = new javax.swing.JLabel();
        Validation1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("THE CRYPTONANIS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZARYAB KHAN\\Desktop\\DesktopApplication\\src\\main\\java\\crytpoexchange\\desktopapplication\\Client\\pictures\\icons8-bitcoin-64 (1).png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 63, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("REGISTRATION FORM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZARYAB KHAN\\Desktop\\DesktopApplication\\src\\main\\java\\crytpoexchange\\desktopapplication\\Client\\pictures\\icons8-clear-symbol-48.png")); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, 43));

        Unique_Id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Unique_Id.setForeground(new java.awt.Color(102, 102, 102));
        Unique_Id.setText("#0");
        jPanel1.add(Unique_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 57, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Admin_Id:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 90, -1));

        L1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L1.setText("FirstName:");
        jPanel1.add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 255, 90, -1));

        FirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FirstName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 235, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("LastName:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 304, 90, -1));

        LastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LastName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 235, -1));

        L3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L3.setText("ValidEmail:");
        jPanel1.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, -1));

        CryptonainName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CryptonainName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(CryptonainName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 235, -1));

        L4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L4.setText("AdminName:");
        jPanel1.add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        Email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Email.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 235, 30));

        L5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L5.setText("Password:");
        jPanel1.add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, -1));

        Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 235, -1));

        L6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        L6.setText("Re-Password:");
        jPanel1.add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 110, -1));

        RePassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RePassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(RePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 235, -1));

        CheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CheckBox.setText("Show Password");
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZARYAB KHAN\\Desktop\\DesktopApplication\\src\\main\\java\\crytpoexchange\\desktopapplication\\Client\\pictures\\icons8-login-48.png")); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, -1, 56));

        Validation2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Validation2.setForeground(new java.awt.Color(255, 51, 102));
        Validation2.setText("Password doesn't match :(");
        jPanel1.add(Validation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 214, -1));

        Validation1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Validation1.setForeground(new java.awt.Color(255, 51, 102));
        Validation1.setText("AdminName already exist :(");
        jPanel1.add(Validation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 214, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZARYAB KHAN\\Desktop\\DesktopApplication\\src\\main\\java\\crytpoexchange\\desktopapplication\\Client\\pictures\\icons8-clear-formatting-48.png")); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 60, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ZARYAB KHAN\\Desktop\\DesktopApplication\\src\\main\\java\\crytpoexchange\\desktopapplication\\Client\\pictures\\icons8-cryptocurrency-mining-64.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        LoginAdministration ld = new LoginAdministration();
        ld.show();
        hide();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
        // TODO add your handling code here:
        Validation2.setVisible(false);
    }//GEN-LAST:event_PasswordMouseClicked

    private void CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxActionPerformed
        // TODO add your handling code here:
        if(CheckBox.isSelected()){
            Password.setEchoChar((char)0);
            RePassword.setEchoChar((char)0);
        }
        else{
            Password.setEchoChar('*');
            RePassword.setEchoChar('*');
        }
    }//GEN-LAST:event_CheckBoxActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        if(RePassword.getText().matches(Password.getText())){
            AdministrationDashBoard adb = new AdministrationDashBoard();
            adb.show();
            hide();
        }
        else{
            Validation2.setVisible(true);
            clear();
        }

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox;
    private javax.swing.JTextField CryptonainName;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JTextField LastName;
    private javax.swing.JPasswordField Password;
    private javax.swing.JPasswordField RePassword;
    private javax.swing.JLabel Unique_Id;
    private javax.swing.JLabel Validation1;
    private javax.swing.JLabel Validation2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
